# Generated by Django 5.0.9 on 2025-06-24 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenDanhMuc', models.CharField(max_length=150)),
                ('MoTa', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenSanPham', models.CharField(max_length=255)),
                ('MoTa', models.TextField(blank=True, null=True)),
                ('Gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SoLuong', models.IntegerField()),
                ('TrangThai', models.CharField(max_length=50)),
                ('NgayDang', models.DateField(auto_now_add=True)),
                ('HinhAnh', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('NguoiBan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='account.seller')),
                ('DanhMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.productcategory')),
            ],
        ),
    ]
