# Generated by Django 5.1.3 on 2025-06-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='HinhAnh2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='HinhAnh3',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='HinhAnh4',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
