# Generated by Django 5.0.9 on 2025-07-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_product_hinhanh2_product_hinhanh3_product_hinhanh4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='TrangThai',
            field=models.CharField(choices=[('con_hang', 'Còn hàng'), ('het_hang', 'Hết hàng')], default='con_hang', max_length=20),
        ),
    ]
