# Generated by Django 5.0.9 on 2025-07-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_cccd_alter_buyer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gioi_tinh',
            field=models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], default='M', max_length=1, null=True),
        ),
    ]
