# Generated by Django 5.0.9 on 2025-06-24 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NgayDatHang', models.DateField(auto_now_add=True)),
                ('TongTien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TrangThaiDonHang', models.CharField(max_length=50)),
                ('DiaChiGiaoHang', models.TextField()),
                ('NguoiMua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuong', models.IntegerField()),
                ('DonGia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ThanhTien', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='home.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoiDungDanhGia', models.TextField()),
                ('SoSao', models.IntegerField()),
                ('NgayDanhGia', models.DateField(auto_now_add=True)),
                ('NguoiBan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='account.seller')),
                ('NguoiMua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='account.buyer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='seller.product')),
            ],
        ),
    ]
