# Generated by Django 5.0.9 on 2025-07-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='TrangThaiDonHang',
            field=models.CharField(choices=[('Đang chờ xác nhận', 'Đang chờ xác nhận'), ('Đang chuẩn bị hàng', 'Đang chuẩn bị hàng'), ('Đang vận chuyển', 'Đang vận chuyển'), ('Đã giao hàng', 'Giao hàng thành công')], default='Đang chờ xác nhận', max_length=50),
        ),
    ]
