# Generated by Django 5.0.9 on 2025-07-02 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_gioi_tinh'),
        ('home', '0003_order_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_comment', to='home.review')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.seller')),
            ],
        ),
    ]
